# Generated by Django 4.2.2 on 2023-06-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('serialCarroceria', models.CharField(max_length=50)),
                ('serialMotor', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('Particular', 'Particular'), ('Transporte', 'Transporte'), ('Carga', 'Carga')], max_length=20)),
                ('precio', models.IntegerField()),
                ('fechaCreacion', models.DateField()),
                ('fechaModificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('modificado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
