# Generated by Django 4.2.2 on 2023-07-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'permissions': [('visualizar_catalogo', 'Visualizar Catalogo')]},
        ),
    ]
